imports:
    - { resource: config.yml }

#framework:
#    validation:
#        cache:                         apc
#

doctrine:
    orm:
        auto_generate_proxy_classes: %kernel.debug%
        default_entity_manager: default

        entity_managers:
            default:
                metadata_cache_driver:
                  type: memcached
                  host: "%memcache_host%"
                  port: "%memcache_port%"
                  instance_class: Memcached
                query_cache_driver:
                  type: memcached
                  host: "%memcache_host%"
                  port: "%memcache_port%"
                  instance_class: Memcached
                result_cache_driver:
                  type: memcached
                  host: "%memcache_host%"
                  port: "%memcache_port%"
                  instance_class: Memcached
#                  second_level_cache:
#                        region_cache_driver:
#                          type: memcached
#                          host: %memcache_host%
#                          port: %memcache_port%
#                          instance_class: Memcached
#                        enabled:              true
#                        regions:
#                            region_name:
#                                cache_driver:
#                                  type: memcached
#                                  host: %memcache_host%
#                                  port: %memcache_port%
#                                  instance_class: Memcached
                auto_mapping: true
                mappings: ~

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
        nested:
            type:  stream
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        console:
            type:  console
