##############################################################################
# Bruery
##############################################################################
bruery_doctrine_orm_admin:
  settings:
    doctrine_cache:
      ttl: 120 #seconds
      enabled: true