##############################################################################
# Sonata Timeline
##############################################################################
sonata_timeline:
    manager_type: orm

    class:
        timeline:         %spy_timeline.class.timeline%
        action:           %spy_timeline.class.action%
        component:        %spy_timeline.class.component%
        action_component: %spy_timeline.class.action_component%

##############################################################################
# Timeline Doctrine
##############################################################################
doctrine:
    orm:
        entity_managers:
            timeline:
                mappings:
                    SonataTimelineBundle: ~
                    SpyTimelineBundle: ~
                    BrueryTimelineBundle: ~
                    AppTimelineBundle: ~

##############################################################################
# Spy Timeline
##############################################################################
spy_timeline:
    drivers:
        orm:
            object_manager: doctrine.orm.timeline_entity_manager
            classes:
                query_builder: ~ # Spy\TimelineBundle\Driver\ORM\QueryBuilder\QueryBuilder
                timeline:         App\TimelineBundle\Entity\Timeline
                action:           App\TimelineBundle\Entity\Action
                component:        App\TimelineBundle\Entity\Component
                action_component: App\TimelineBundle\Entity\ActionComponent

    filters:
        data_hydrator:
            priority:             20
            service:              spy_timeline.filter.data_hydrator
            filter_unresolved:    false
            locators:
                - spy_timeline.filter.data_hydrator.locator.doctrine_orm

    paginator: spy_timeline.paginator.knp

